#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'JHGrandPopupViewDemo' do

#pod 'JHGrandPopupView', '~> 1.0.0'
pod 'JHGrandPopupView', :path => '../'
pod 'SnapKit', '~> 5.0.0'

end
